### PR TITLE
Create additions.txt

### PR DESCRIPTION
**Pull request by AmrShoukry2**
I have **created** a new file called additions.txt

### CODE REVIEW

**Comment by AmrShoukry2** [comment]
please accept my changes!

**Comment by AmrShoukry2** [comment]
iam leaving

**Comment by AmrShoukry2** [comment]
ok i am opening again

**Comment by AmrShoukry** [comment]
ok i am accepting it

**Comment by AmrShoukry** [comment]
or i am leaving it too!

**Comment by AmrShoukry** [comment]
I opened it again

**Pull request merged**
